UNITY-7762 add isproductnumbervisible
ePages-de/epages-docs pull request #1231
Opened 2022-05-20 12:11 UTC by mhoehn

2022-07-28 14:32 UTC, dkluever22 requested changes
@mhoehn I would change the wording slightly. Please have a look at my suggestions.

2022-07-28 14:32 UTC, dkluever22 commented on apps/data-types.md
> +| isProductNumberVisible | boolean | Indicates if the product number can be shown in the storefront. |
```suggestion
| isProductNumberVisible | boolean | Indicates if the product number is displayed in the storefront. |
```

2022-07-28 14:32 UTC, dkluever22 commented on apps/data-types.md
> +| isProductNumberVisible | boolean | Indicates if the product number can be shown in the storefront. |
```suggestion
| isProductNumberVisible | boolean | Indicates if the product number is displayed in the storefront. |
```

2022-08-10 12:08 UTC, ywolpers approved these changes

2022-08-10 12:27 UTC, merged