Deprecate listPrice and manufacturerPrice in storefront events
ePages-de/epages-docs pull request #1281
Opened 2023-02-10 13:28 UTC by depoulo

EPUI-1830

2023-02-10 13:28 UTC, depoulo commented on apps/change-log.md
> +## 2023-0?-??
@ePages-de/team-emerald FYI

2023-02-10 13:29 UTC, depoulo commented on apps/change-log.md
> +
FYI @ePages-de/team-emerald due to the release cycle, I left out the dates, for you to update later.

2023-02-10 15:16 UTC, Aliamondo approved these changes

2023-02-14 14:34 UTC, dkluever22 requested changes
If you agree to the changes I suggested, it would be important to wait until Thursday, February 16th, before merging this PR.

2023-02-14 14:34 UTC, dkluever22 commented on apps/change-log.md
> +## 2023-0?-??
I would say here we use the dates for the upcoming roll out of 7.80 to announce the deprecation

```suggestion
## 2023-02-16
```

2023-02-15 09:37 UTC, dkluever22 approved these changes

2023-02-16 12:09 UTC, merged