UNITY-8284 create-variation-products
ePages-de/epages-docs pull request #1296
Opened 2023-03-29 13:16 UTC by mhoehn

2023-04-05 12:19 UTC, dkluever22 requested changes
@mhoehn I have reviewed the PR and left you a couple of comments. Please take a look and let me know if you have any questions :)

2023-04-05 12:19 UTC, dkluever22 commented on apps/data-types.md
> +| visibleAfterCreation | boolean | Indicates if the new variation products are displayed in the shop after creation. |
```suggestion
| visibleAfterCreation | boolean | Indicates if the new product variations are displayed in the shop after creation. |
```

2023-04-05 12:19 UTC, dkluever22 commented on apps/data-types.md
> +| productType | string | Unique name (alias) of the product type. |
```suggestion
| productType | string | The unique name of the product type. |
```

2023-04-05 13:24 UTC, mhoehn commented on _raml/apps/products/examples/post_product_productid_variations_request.json
> +  "productType":"Shoe",
yess, Maik is then using the same attributes and values

2023-04-06 13:00 UTC, dkluever22 commented on _raml/apps/products/examples/post_product_productid_variations_request.json
> +              "value": "in-ear"
```suggestion
              "value": "In-ear"
```

2023-04-06 13:00 UTC, dkluever22 commented on _raml/apps/products/examples/post_product_productid_variations_request.json
> +              "value": "on-ear"
```suggestion
              "value": "On-ear"
```

2023-04-06 13:07 UTC, dkluever22 approved these changes

2023-05-11 11:23 UTC, merged