UNITY-8613 oder units
ePages-de/epages-docs pull request #1323
Opened 2023-09-28 11:43 UTC by mhoehn

2023-10-26 05:55 UTC, mhoehn commented on _raml/apps/products/examples/post_product_find_response.json
> +      "priceQuantity": 1,
added

2023-10-26 08:55 UTC, dkluever22 requested changes
Please have another look at my suggestions. Furthermore, I think that we need to adjust the files _/get_product_productid_response.json_, _/patch_product_productid_response.json_ and _/post_product_response.json_ as well.

2023-10-26 08:55 UTC, dkluever22 commented on _raml/apps/products/examples/get_product_productid_crossselling_response.json
> +        "orderUnit": "piece",
```suggestion
        "orderUnit": "piece(s)",
```

2023-10-26 08:55 UTC, dkluever22 commented on _raml/apps/products/examples/post_product_find_response.json
> +      "orderUnit": "piece",
```suggestion
      "orderUnit": "piece(s)",
```

2023-10-26 08:55 UTC, dkluever22 commented on _raml/apps/products/examples/post_product_find_response.json
> +      "orderUnit": "piece",
```suggestion
      "orderUnit": "piece(s)",
```

2023-10-26 08:55 UTC, dkluever22 commented on apps/data-types.md
> +| orderUnit | string | The product order unit. Can be *byte(s)*, *kilobyte(s)*, *megabyte(s)*, *gigabyte(s)*, *terabyte(s)*, *gram(s)*, *kilogram(s)*, *milligram(s)*, *ounce(s)*, *pound(s)*, *tone(s)
```suggestion
| orderUnit | string | The product order unit. Can be *byte(s)*, *kilobyte(s)*, *megabyte(s)*, *gigabyte(s)*, *terabyte(s)*, *gram(s)*, *kilogram(s)*, *milligram(s)*, *ounce(s)*, *pound(s)*, *tone(s)*, *liter(s)*, *cubic foot*, *cubic feet*, *cubic inch(es)*, *cubic metre(s)*, *cubic yard(s)*, *fluid ounce(s)*, *gallon(s)*, *milliliter(s)*, *quart(s)*, *meter(s)*, *centimeter(s)*, *foot*, *inch(s)*, *kilometer(s)*, *millimeter(s)*, *yard(s)*, *piece(s)*, *bottle(s)*, *box(es)*, *can(s)*, *capsule(s)*, *carton(s)*, *glass(es)*, *kit(s)*, *pack(s)*, *packet(s)*, *pair(s)*, *roll(s)*, *set(s)*, *sheet(s)*, *ticket(s)*, *unit(s)*, *second(s)*, *day(s)*, *hour(s)*, *minute(s)*, *month(s)*, *night(s)*, *week(s)*, *year(s)*, *square meter(s)*, *square centimeter(s)*, *square foot*, *square feet*, *square inch(es)*, *square millimeter(s)* or *square yard(s)*. The localised name of the unit is displayed. | 
```

2023-10-26 08:55 UTC, dkluever22 commented on apps/data-types.md
> +| orderUnit | string | The product order unit. Can be *byte(s)*, *kilobyte(s)*, *megabyte(s)*, *gigabyte(s)*, *terabyte(s)*, *gram(s)*, *kilogram(s)*, *milligram(s)*, *ounce(s)*, *pound(s)*, *tone(s)
```suggestion
| orderUnit | string | The product order unit. Can be *byte(s)*, *kilobyte(s)*, *megabyte(s)*, *gigabyte(s)*, *terabyte(s)*, *gram(s)*, *kilogram(s)*, *milligram(s)*, *ounce(s)*, *pound(s)*, *tone(s)*, *liter(s)*, *cubic foot*, *cubic feet*, *cubic inch(es)*, *cubic metre(s)*, *cubic yard(s)*, *fluid ounce(s)*, *gallon(s)*, *milliliter(s)*, *quart(s)*, *meter(s)*, *centimeter(s)*, *foot*, *inch(s)*, *kilometer(s)*, *millimeter(s)*, *yard(s)*, *piece(s)*, *bottle(s)*, *box(es)*, *can(s)*, *capsule(s)*, *carton(s)*, *glass(es)*, *kit(s)*, *pack(s)*, *packet(s)*, *pair(s)*, *roll(s)*, *set(s)*, *sheet(s)*, *ticket(s)*, *unit(s)*, *second(s)*, *day(s)*, *hour(s)*, *minute(s)*, *month(s)*, *night(s)*, *week(s)*, *year(s)*, *square meter(s)*, *square centimeter(s)*, *square foot*, *square feet*, *square inch(es)*, *square millimeter(s)* or *square yard(s)*. The localised name of the unit is displayed. | 
```

2023-10-26 12:50 UTC, dkluever22 approved these changes

2023-12-13 15:19 UTC, dkluever22 requested changes
@mhoehn While reviewing another PR I have noticed a few errors in the `orderUnit` description.

2023-12-13 15:19 UTC, dkluever22 commented on apps/data-types.md
> +| orderUnit | string | The product order unit. Can be *byte(s)*, *kilobyte(s)*, *megabyte(s)*, *gigabyte(s)*, *terabyte(s)*, *gram(s)*, *kilogram(s)*, *milligram(s)*, *ounce(s)*, *pound(s)*, *tone(s)
```suggestion
| orderUnit | string | The product order unit. Can be one of *byte(s)*, *kilobyte(s)*, *megabyte(s)*, *gigabyte(s)*, *terabyte(s)*, *gram(s)*, *kilogram(s)*, *milligram(s)*, *ounce(s)*, *pound(s)*, *ton(s)*, *liter(s)*, *milliliter(s)*, *cubic foot*, *cubic feet*, *cubic inch(es)*, *cubic meter(s)*, *cubic yard(s)*, *fluid ounce(s)*, *gallon(s)*, *quart(s)*, *meter(s)*, *centimeter(s)*, *foot*, *feet*, *inch(es)*, *kilometer(s)*, *millimeter(s), *yard(s)*, *piece(s)*, *bottle(s)*, *box(es)*, *can(s)*, *capsule(s)*, *crate(s),* *glass(es)*, *kit(s)*, *pack(s)*, *package(s)*, *pair(s)*, *roll(s)*, *set(s)*, *sheet(s)*, *ticket(s)*, *unit(s)*, *second(s)*, *minute(s)*, *hour(s)*, *day(s)*, *night(s)*, *week(s)*, *month(s)*, *year(s)*, *square meter(s)*, *square centimeter(s)*, *square foot*, *square feet*, *square inch(es)*, *square millimeter(s)* or *square yard(s)*. The localised name of the unit is displayed. | 
```

2023-12-13 15:19 UTC, dkluever22 commented on apps/data-types.md
> +| orderUnit | string | The product order unit. Can be *byte(s)*, *kilobyte(s)*, *megabyte(s)*, *gigabyte(s)*, *terabyte(s)*, *gram(s)*, *kilogram(s)*, *milligram(s)*, *ounce(s)*, *pound(s)*, *tone(s)
```suggestion
| orderUnit | string | The product order unit. Can be one of *byte(s)*, *kilobyte(s)*, *megabyte(s)*, *gigabyte(s)*, *terabyte(s)*, *gram(s)*, *kilogram(s)*, *milligram(s)*, *ounce(s)*, *pound(s)*, *ton(s)*, *liter(s)*, *milliliter(s)*, *cubic foot*, *cubic feet*, *cubic inch(es)*, *cubic meter(s)*, *cubic yard(s)*, *fluid ounce(s)*, *gallon(s)*, *quart(s)*, *meter(s)*, *centimeter(s)*, *foot*, *feet*, *inch(es)*, *kilometer(s)*, *millimeter(s), *yard(s)*, *piece(s)*, *bottle(s)*, *box(es)*, *can(s)*, *capsule(s)*, *crate(s),* *glass(es)*, *kit(s)*, *pack(s)*, *package(s)*, *pair(s)*, *roll(s)*, *set(s)*, *sheet(s)*, *ticket(s)*, *unit(s)*, *second(s)*, *minute(s)*, *hour(s)*, *day(s)*, *night(s)*, *week(s)*, *month(s)*, *year(s)*, *square meter(s)*, *square centimeter(s)*, *square foot*, *square feet*, *square inch(es)*, *square millimeter(s)* or *square yard(s)*. The localised name of the unit is displayed. | 
```

2023-12-14 11:23 UTC, dkluever22 approved these changes

2024-02-21 20:03 UTC, dkluever22 reviewed
@mhoehn I have adjusted the description of `priceQuantity` a little. One more question: doesn't `quantityPrice` need to be added to the data types as well?

2024-03-21 09:08 UTC, merged